version: '3.0'

services:
  rssproxy:
    image: 192.168.50.135:4567/homelab/rssproxy:latest
    volumes:
      - /mnt/user/appdata/rssproxy/config.yaml:/app/config.yaml
    ports:
      - 1201:1200
    restart: always